"content_dir": "/home/joe/Coding/cms/content/content"
"static_dir": "/home/joe/Coding/cms/content/static"

"default_page_config":
  "sitename": "Lecture notes"
  "extra_head": []
  "extra_body": []
  "extra_script": []
  "extra_style": []
  "js_scripts": []
  "stylesheets": []
  "users":
    - "anon"
  "template": "base.tmpl"
