"content_dir": "/home/joe/uni/notes-site/content"
"template_dirs":
  - "/home/joe/Coding/cms/example_templates"

"static_dirs":
  - "/home/joe/uni/notes-site/static"
  - "/home/joe/Coding/cms/example_static"

"default_page_config":
  "sitename": "Lecture notes"
  "extra_head": []
  "extra_body": []
  "extra_script": []
  "extra_style": []
  "js_scripts": []
  "stylesheets": []
  "users":
    - "anon"
  "template": "base.tmpl"
