import os

from jinja2 import Environment, FileSystemLoader
from flask import Flask, abort
import yaml

from page import Page

class Site(object):
    def __init__(self):
        self.content_dir = "content"
        self.templates_dir = "cms/templates"
        self.config_file = os.path.join(self.content_dir, "config.yaml")

    def generate_index(self, start_dir=None, depth=None):
        """Recursively generate a page index from the given starting directory.
        The listing is returned as an array of pages, where each page is
        represented in the form {"title": ..., "href": ..., children": [...]},
        where the children array may contain other pages.

        The depth parameter specifies the number of levels to go down, or None to
        give the full index"""
        start_dir = start_dir or self.content_dir
        listing = []

        dir_listing = os.listdir(start_dir)

        for entry in dir_listing:
            path = os.path.join(start_dir, entry)
            if os.path.isdir(path):

                # Only recurse if depth > 1
                if depth is None or depth > 1:
                    new_depth = None if depth is None else depth - 1
                    children = self.generate_index(start_dir=path, depth=new_depth)
                else:
                    children = []

                new_dir = {
                    "title": Page.format_page_name(path),
                    "url": self.get_url_for(path),
                    "children": children,
                    "path": os.path.join(path, "index.md")
                }
                listing.append(new_dir)

            elif entry.endswith(".md") and entry != "index.md":
                listing.append({
                    "title": Page.format_page_name(path),
                    "url": self.get_url_for(path),
                    "children": [],
                    "path": path
                })

        return listing

    def flatten_index(self, index):
        """Flatten a site index generated by generate_index()"""

        def flatten_page(page):
            pages = []
            p = page.copy()

            if p["children"]:
                for child_page in p["children"]:
                    pages += flatten_page(child_page)

            del p["children"]
            pages.append(p)
            return pages

        flat = []
        for page in index:
            flat += flatten_page(page)
        return flat

    def get_url_for(self, path):
        """Return the URL for the page at the specified path"""

        # Remove .md if present
        if path.endswith(".md"):
            path = path[:-3]

        # Split path by '/'s and go through each component, stopping after we reach
        # the content dir
        split_path = path.split(os.sep)
        for i, k in enumerate(split_path):
            if k == site.content_dir:
                i += 1
                break

        # Join together all components after the content dir
        return "/" + "/".join(split_path[i:])

    def get_site_config(self):
        """Load config file that serves as a base for every page"""
        with open(self.config_file) as f:
            return yaml.load(f) or {}


app = Flask(__name__)
site = Site()
# jinja2 environment for loading templates
env = Environment(loader=FileSystemLoader(site.templates_dir))

@app.route("/<path:url>/")
@app.route("/", defaults={"url": ""})
def view_page(url):
    """Render the specified page"""
    url = os.sep + url

    # Get the site index and find page by URL
    index = site.generate_index()
    all_pages = site.flatten_index(index)
    page_info = [p for p in all_pages if p["url"] == url]

    if page_info:
        default_config = site.get_site_config()["default_page_config"]

        # Set site index and header links
        default_config["site_index"] = index
        default_config["header_links"] = site.generate_index(depth=2)

        page = Page(page_info[0]["path"], default_config)
        return page.to_html(env)

    else:
        abort(404)
